name: pubspec_helper
description: Command line tools that helps you maintain pubspec.
version: 0.0.1
# homepage: https://www.example.com
# author: Gurleen Sethi <sarusethi@rocketmail.com>

environment:
  sdk: '>=2.2.0 <3.0.0'

dependencies:
  path: ^1.4.1
  args: ^1.5.2

dev_dependencies:
  pedantic: ^1.0.0
  test: ^1.0.0
